export { default as Homepage } from './Homepage'
export { default as SearchingForDealsPage } from './SearchingForDealsPage'
export { default as CarDealsList } from './CarDealsListPage'
export { default as CarDetailsPage } from './CarDetailsPage'
export { default as AnimatedRoutes } from './animated-routes'